name: Discord Notification

on:
  push:
    branches:
      - main  # ou ta branche principale

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Send Discord webhook message
      uses: ilshidur/action-discord@v2
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
        message: "🚀 Nouveau push sur le repo star-stable-online-rich-presence-discord !"
