name: 📢 Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: 🔔 Envoyer une notification Discord
        uses: tsickert/discord-webhook@v1.0.4
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
            🚀 Nouveau push sur **${{ github.repository }}**
            👤 Auteur : **${{ github.actor }}**
            💬 Message : _${{ github.event.head_commit.message }}_
            🔗 [Voir le commit](${{ github.event.head_commit.url }})
